import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

const Home: NextPage = () => {
  const [{ data, error, fetching }] = useQuery({ query: PRODUCT_QUERY });
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hi next</h1>
      </main>
    </div>
  );
};

export default Home;
